# Generated by Django 5.2.11 on 2026-02-20 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task_order', models.JSONField()),
                ('random_seed', models.CharField(max_length=64)),
                ('device_meta', models.JSONField(default=dict)),
                ('timezone_offset_minutes', models.SmallIntegerField(blank=True, null=True)),
                ('completion_status', models.CharField(choices=[('complete', 'Complete'), ('abandoned', 'Abandoned'), ('in_progress', 'In Progress')], default='in_progress', max_length=20)),
                ('quality_flags', models.JSONField(default=list)),
                ('is_practice', models.BooleanField(default=False)),
                ('prompt_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cognitive_sessions', to='notifications.promptevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valence', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('arousal', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('stress', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('sharpness', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mood_rating', to='tasks.cognitivesession')),
            ],
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=50)),
                ('task_version', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('trial_data', models.JSONField()),
                ('summary_metrics', models.JSONField()),
                ('session_index_overall', models.PositiveIntegerField()),
                ('session_index_per_task', models.PositiveIntegerField()),
                ('is_acclimatisation', models.BooleanField(default=False)),
                ('is_partial', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to='tasks.cognitivesession')),
            ],
        ),
        migrations.AddIndex(
            model_name='cognitivesession',
            index=models.Index(fields=['user', 'started_at'], name='tasks_cogni_user_id_04fd77_idx'),
        ),
        migrations.AddIndex(
            model_name='cognitivesession',
            index=models.Index(fields=['user', 'completion_status'], name='tasks_cogni_user_id_220636_idx'),
        ),
    ]
