# Generated by Django 5.2.11 on 2026-02-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitivesession',
            name='derived_variables',
            field=models.JSONField(default=dict),
        ),
    ]
