# Generated by Django 5.2.11 on 2026-02-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_cognitivesession_derived_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Task configuration',
                'verbose_name_plural': 'Task configurations',
                'ordering': ['task_type'],
            },
        ),
    ]
