# Generated by Django 5.2.11 on 2026-02-28 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskconfig_seed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled_task_types', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User task preference',
                'verbose_name_plural': 'User task preferences',
            },
        ),
    ]
