# Generated by Django 5.2.11 on 2026-02-20 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlungeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('water_temp_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('temp_measured', models.BooleanField(default=False)),
                ('immersion_depth', models.CharField(choices=[('waist', 'Waist'), ('chest', 'Chest'), ('neck', 'Neck')], max_length=10)),
                ('context', models.CharField(choices=[('bath', 'Bath'), ('lake', 'Lake'), ('sea', 'Sea'), ('cryotherapy', 'Cryotherapy'), ('other', 'Other')], max_length=20)),
                ('breathing_technique', models.CharField(blank=True, max_length=100)),
                ('perceived_intensity', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('thermal_sensation', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plunge_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'timestamp'], name='plunges_plu_user_id_c9a3f4_idx')],
            },
        ),
    ]
