# Generated by Django 5.2.11 on 2026-02-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plunges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plungelog',
            name='thermal_sensation',
        ),
        migrations.AlterField(
            model_name='plungelog',
            name='perceived_intensity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'No effort'), (2, 'Mild'), (3, 'Moderate'), (4, 'Hard'), (5, 'Extreme')]),
        ),
    ]
