# Generated by Django 5.2.11 on 2026-02-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plunges', '0002_remove_thermal_sensation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plungelog',
            name='context',
            field=models.CharField(choices=[('plunge_pool', 'Plunge pool'), ('bath', 'Bath'), ('lake', 'Lake'), ('sea', 'Sea'), ('cryotherapy', 'Cryotherapy'), ('other', 'Other')], max_length=20),
        ),
    ]
