# Generated by Django 5.2.11 on 2026-02-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plunges', '0003_add_plunge_pool_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='plungelog',
            name='pre_hot_treatment',
            field=models.CharField(blank=True, choices=[('sauna', 'Sauna'), ('steam_room', 'Steam room')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plungelog',
            name='pre_hot_treatment_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
