# Generated by Django 5.2.11 on 2026-02-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plunges', '0004_add_pre_hot_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='plungelog',
            name='exercise_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plungelog',
            name='exercise_timing',
            field=models.CharField(blank=True, choices=[('before', 'Before'), ('after', 'After')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plungelog',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('cardio', 'Cardio'), ('weights', 'Weights')], max_length=10, null=True),
        ),
    ]
