# Generated by Django 5.2.11 on 2026-02-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plunges', '0005_add_exercise_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plungelog',
            name='head_submerged',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
