# Generated by Django 5.2.11 on 2026-02-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plunges', '0006_add_head_submerged'),
    ]

    operations = [
        migrations.AddField(
            model_name='plungelog',
            name='strava_activity_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
