# Generated by Django 5.2.11 on 2026-02-20 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covariates', '0001_initial'),
        ('tasks', '0002_cognitivesession_derived_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCovariate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caffeine_since_last_session', models.BooleanField(blank=True, null=True)),
                ('minutes_since_last_meal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cold_hands', models.BooleanField(blank=True, null=True)),
                ('wet_hands', models.BooleanField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_covariate', to='tasks.cognitivesession')),
            ],
        ),
    ]
