# Generated by Django 5.2.11 on 2026-02-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covariates', '0002_sessioncovariate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklycovariate',
            name='gi_symptoms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
