# Generated by Django 5.2.11 on 2026-02-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covariates', '0003_alter_weeklycovariate_gi_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycovariate',
            name='menstruation_today',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'Not applicable')], max_length=3, null=True),
        ),
    ]
