# Generated by Django 5.2.11 on 2026-02-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covariates', '0004_add_menstruation_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycovariate',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=2, editable=False),
        ),
        migrations.AddField(
            model_name='weeklycovariate',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
    ]
