# Generated by Django 5.2.11 on 2026-02-21 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onesignal_player_id', models.CharField(blank=True, max_length=255)),
                ('push_enabled', models.BooleanField(default=True)),
                ('morning_window_start', models.TimeField(default='08:00')),
                ('evening_window_start', models.TimeField(default='18:00')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
