# Generated by Django 5.2.11 on 2026-02-21 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationprofile',
            name='evening_window_start',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='notificationprofile',
            name='morning_window_start',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
