# Generated by Django 5.2.11 on 2026-02-20 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_pseudonymised_id_consentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('handedness', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('ambidextrous', 'Ambidextrous')], max_length=20)),
                ('plunge_years', models.DecimalField(decimal_places=1, max_digits=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
